[package]
name = "micropython-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
venice-program-table.workspace = true
hashbrown.workspace = true
thiserror = { version = "2.0.14", default-features = false }
