[package]
name = "micropython-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
venice-program-table.workspace = true
bitflags = "2.9.2"
thiserror = { version = "2.0.14", default-features = false }
