[package]
name = "venice"
version = "0.1.0"
edition = "2024"

[features]
default = []
simulated = []

[dependencies]
cty = "0.2.2"
hashbrown = "0.15.4"
no_std_io = "0.6.0"
spin = "0.10.0"
talc = "4.4.3"
vex-sdk = "0.26.0"

[dependencies.lazy_static]
version = "1.5.0"
features = ["spin_no_std"]

[profile.release]
lto = true
strip = true
opt-level = "s"
