[package]
name = "venice"
license = "MPL-2.0"
version = "0.1.0"
edition = "2024"

[dependencies]
cty = "0.2.2"
hashbrown = "0.15.4"
no_std_io = "0.6.0"
paste = "1.0.15"
spin = "0.10.0"
talc = "4.4.3"
vex-sdk = "0.26.0"

[dependencies.venice-program-table]
git = "https://github.com/venice-v5/venice-program-table.git"
rev = "2fa8d392bb45a7b69e93f5a7e668ad4bca18007d"

[dependencies.lazy_static]
version = "1.5.0"
features = ["spin_no_std"]

[profile.release]
lto = true
strip = true
opt-level = "s"

[build-dependencies]
format-bytes = "0.3.0"
regex = "1.11.1"
