"""
Venice implements its own async runtime on top of Micropython. `vasyncio` provides primitives for working with async Python in Venice.
"""
from __future__ import annotations
from typing import Any
from . import TimeUnit

class EventLoop:
    def __init__(self) -> None: ...

    def spawn(self, coro: Any) -> Task: ...

    def run(self) -> None: ...

class Sleep:
    def __init__(self, interval: float, unit: TimeUnit) -> None: ...

class Task:
    ...

def run(coro: Any) -> None: ...

def spawn(coro: Any) -> Task: ...

def get_running_loop() -> EventLoop: ...